name: Run Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        cmake -S. -Bbuild -G "Unix Makefiles" -DENABLE_TESTING=ON
    - name: build
      working-directory: ./build
      run: |
        make -j
    - name: test
      working-directory: ./build
      run: |
        ctest -C --output-on-failure --verbose
    - name: setup_lcov
      if: contains(matrix.os, 'ubuntu')
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: coverage
      if: contains(matrix.os, 'ubuntu')
      working-directory: ./build
      run: |
        lcov --directory . --capture --output-file ./code_coverage.info --rc lcov_branch_coverage=1
        genhtml code_coverage.info --branch-coverage --output-directory ./coverage/
    - name: artifacts
      if: contains(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report
        path: ./build/coverage/
